os:
  - linux

language:
  - cpp

before_install:
    - set -e -x
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo add-apt-repository --yes ppa:beineri/opt-qt55
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt5-qmake qt55base qt55declarative qt55quickcontrols qt55script

script:
    #- set -e -x
    - /opt/qt55/bin/qt55-env.sh
    - qmake
    # qmake -qt=qt5
    - make
    # qmake -qt=qt5 -v
    # qmake -qt=qt5
    # make