os:
  - linux

language:
  - cpp

install:
    - sudo pip install cpp-coveralls
    - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository --yes ppa:beineri/opt-qt55
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-4.8 libc6-i386
    - sudo apt-get install -qq qt-latest
    - export CXX="g++-4.8"
    - export CC="gcc-4.8"

script:
    - QTDIR="/opt/qt55"
    - PATH="$QTDIR/bin:$PATH"
    - qt55-env.sh 

    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=--coverage -DCMAKE_C_FLAGS=--coverage
    #- qmake TravisTest.pro CONFIG+=debug "QT += testlib"
    #- qmake
    - make

    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3

    - ./TravisTest --test
    - ls

after_success:
    - coveralls --build-root "build"
