os:
  - linux

language:
  - cpp

compiler:
    - g++

addons:
    apt: 
        sources:
            - ubuntu-toolchain-r-test

        packages:
            - python-yaml
            - libc6-i386

install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8"

    - $CXX --version

    - sudo pip install cpp-coveralls
    - sudo add-apt-repository --yes ppa:beineri/opt-qt55
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt-latest

script:
    - QTDIR="/opt/qt55"
    - PATH="$QTDIR/bin:$PATH"
    - qt55-env.sh 

    - qmake -v
    - qmake TravisTest.pro CONFIG+=debug "QT += testlib"

    - make -v
    - make

    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3

    - ls -R
    - ./TravisTest --test

after_success:
    - cd src
    - exclude_regexs=('.*/moc_.*' '.*\.moc$' '.*_automoc\..*' '.*/ui_.*' '.*/qrc_.*' '.*CMake.*' '.*/tests/.*')
    - arguments=()
    - for regex in "${exclude_regexs[@]}"; do arguments+=(--exclude-pattern "$regex"); done
    - coveralls "${arguments[@]}"