os:
  - linux

language:
  - cpp

before_install:
    - sudo pip install cpp-coveralls

install:
    - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository --yes ppa:beineri/opt-qt55
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-4.8 libc6-i386
    - sudo apt-get install -qq qt-latest
    - export CXX="g++-4.8"
    - export CC="gcc-4.8"

script:
    - QTDIR="/opt/qt55"
    - PATH="$QTDIR/bin:$PATH"
    - qt55-env.sh 

    - qmake TravisTest.pro CONFIG+=debug "QT += testlib"
    - qmake
    - make

after_success:
    - coveralls --build-root "build"
