os:
  - linux

language:
  - cpp

before_install:
    #- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo add-apt-repository --yes ppa:beineri/opt-qt55
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt-latest

script:
    #- QMAKE="qmake"
    #- /opt/qt55/bin/qt55-env.sh
    #- qmake
    # qmake -qt=qt5
    #- $QMAKE
    #- $QMAKE
    - qmake -v
    - ls /usr/lib/x86_64-linux-gnu
    - make