os:
  - linux

language:
  - cpp

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt5-qmake qt55base qt55declarative qt55quickcontrols qt55script

script:
    - qmake -qt=qt5 -v
    - qmake -qt=qt5
    - make